- gazebo_ros2_control/CMakeLists.txt
- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_ros2_control_plugin.hpp
- gazebo_ros2_control/package.xml
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Related to this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/10
> Used gazebo_ros::Node

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Parameters in ROS 2 are associated to a node. By default the `robot_description` parameter will be requested to `/robot_state_pusblisher` but defining `robotParamNode` this node could be changed.
> Added robotParamNode to gazebo_ros2_control plugin

- gazebo_ros2_control/include/gazebo_ros2_control/robot_hw_sim.hpp
Related to this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/21
> Removed compilation warnigns

- .github/workflows/ci.yaml
- gazebo_ros2_control/include/gazebo_ros2_control/robot_hw_sim.hpp
- gazebo_ros2_control/src/default_robot_hw_sim.cpp
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Return values have change in `hardware_interface` and `controller_interface` 
> Update with ros2_control: return types (hardware_interface and controller_interface) 

- .github/workflows/ci.yaml
- gazebo_ros2_control/CMakeLists.txt
- gazebo_ros2_control/include/gazebo_ros2_control/default_robot_hw_sim.hpp
- gazebo_ros2_control/package.xml
- gazebo_ros2_control/src/default_robot_hw_sim.cpp
This PR adds velocity and position PID
This PR is based on this other PR https://github.com/ros-controls/control_toolbox/pull/97
> Added position and velocity PID

- .github/workflows/ci.yaml
- Docker/Dockerfile
- gazebo_ros2_control/include/gazebo_ros2_control/default_robot_hw_sim.hpp
- gazebo_ros2_control/src/default_robot_hw_sim.cpp
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
- gazebo_ros2_control_demos/CMakeLists.txt
- gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml
- gazebo_ros2_control_demos/examples/example_velocity.cpp
- gazebo_ros2_control_demos/package.xml
- gazebo_ros2_control_demos/urdf/test_cart_velocity.xacro.urdf
Updated with recent ros2_control changes
> Updated with recent ros2_control changes

- gazebo_ros2_control/CMakeLists.txt
- gazebo_ros2_control/src/gazebo_system.cpp
Signed-off-by: Karsten Knese <Karsten1987@users.noreply.github.com>
> make compile on osx

- gazebo_ros2_control/CMakeLists.txt
Signed-off-by: Chen Bainian <chenbn@artc.a-star.edu.sg>
Include directories cannot be linked through `ament_target_dependencies()` due to the `include` path is not inside `gazebo_ros2_control_INCLUDE_DIRS`.
This small change will fix it.
> Expose include path inside INCLUDE_DIRS

- gazebo_ros2_control_demos/launch/cart_example_effort.launch.py
- gazebo_ros2_control_demos/launch/cart_example_position.launch.py
- gazebo_ros2_control_demos/launch/cart_example_velocity.launch.py
I used `ros2control` to load the controllers as @Karsten1987 described in this comment https://github.com/ros-simulation/gazebo_ros2_control/pull/60#issuecomment-780732126
This PR builds on top of your PR @Karsten1987, do you mind to have a look ?
> Load controllers in the example launch files

- gazebo_ros2_control/CMakeLists.txt
- gazebo_ros2_control/package.xml
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
fixes #59 
With this PR, the actual parameters are being set:
```
➭ ros2 param list
...
/controller_manager:
joint_state_controller.type
joint_trajectory_controller.type
update_rate
use_sim_time
```
While implementing this, I found actually a second bug in which all specified controllers in the loaded yaml file would be loaded. It didn't show in the example, however this would necessarily lead to resource conflicts when more than one controller use the same command interface.
> add ros parameters file to node context

- gazebo_ros2_control_demos/package.xml
One-line addition to the package.xml definition for the demos so that rosdep knows to install the ros2_control package.
Fixes #74 
Since the Docker/Dockerfile performs a clone of the repository@master, you can replace this line locally with my repository and branch and then build and test with Docker.
```sh
sed -i 's@git clone https://github.com/ros-simulation/gazebo_ros2_control@git clone --single-branch --branch demo-dependency-fix https://github.com/CSharpRon/gazebo_ros2_control@' Docker/Dockerfile 
cd Docker
docker build -t gazebo_ros2_control_demos:test .
docker run gazebo_ros2_control_demos:test
```
> Adding ros2_control dependency to demos (#74)

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
This prevents a SIGABRT in gzserver when stopping gazebo due to the executor thread being aborted, which triggers a core dump.  This patch instead ensures a clean exit, since rclcpp::ok() returns true while gazebo is shutting down.
Note: I'm not sure why the controller manager's node must be removed from the executor, but otherwise the join() will remain blocked and prevent gzserver from stopping even with a SIGTERM.
> Join with the controller manager's executor thread on exit

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Currently, the loaded controllers do not receive the remappings and namespace info from the sdf. This commit adds this information to the generated argument list so that they are forwarded to subsequently started nodes.
> Forward sdf ros remappings to loaded controllers

- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system.hpp
- gazebo_ros2_control/src/gazebo_system.cpp
- gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml
- gazebo_ros2_control_demos/launch/cart_example_velocity.launch.py
- gazebo_ros2_control_demos/urdf/test_cart_position.xacro.urdf
- gazebo_ros2_control_demos/urdf/test_cart_velocity.xacro.urdf
Add state interfaces for gazebo sensors.
This allows sensors from being read directly from ROS control without going through ROS topics, which can better replicate real hardware where the sensor is read through the same bus as the actuators.
I took the liberty of establishing some standard interface names for IMU: "orientation.x", "linear_acceleration.x" and "angular_velocity.x". And obviously for y, z and w in the case of the orientation quaternion.
Maybe we could put this somewhere more standard , thoughts @bmagyar?
If this looks good, I'll do the same for the FT Sensor. 
We've been using this for years in ROS1 in https://github.com/pal-robotics/pal_hardware_gazebo/blob/melodic-devel/src/pal_hardware_gazebo.cpp but we think it will benefit more people here in ROS2.
> Add Imu and FT state interfaces

- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system.hpp
- gazebo_ros2_control/src/gazebo_system.cpp
Looking at the code, I noticed that the GazeboSystem creates state and command interfaces in 2 places:
1. [In the initSim method](https://github.com/ros-simulation/gazebo_ros2_control/blob/956e7706338fd4fd1a2ef733ad54740d07e9a67a/gazebo_ros2_control/src/gazebo_system.cpp#L143-L185). It creates only the handles for the interfaces defined in the URDF. 
2. [In export methods](https://github.com/ros-simulation/gazebo_ros2_control/blob/956e7706338fd4fd1a2ef733ad54740d07e9a67a/gazebo_ros2_control/src/gazebo_system.cpp#L199-L267). It creates handles for all interfaces (effort, velocity, position), regardless of whether they are defined in the URDF, and exports them to the Resource Manager.
This makes the handles created in 1. completely redundant (unless I'm missing something), as they are not …
> Export interfaces created in init

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
This fixes ros-controls/ros2_controllers#253
I haven't tested it with all the available controllers though.
> Pass ROS time instead of SYSTEM time to update function

- gazebo_ros2_control/CMakeLists.txt
- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system_interface.hpp
- gazebo_ros2_control/package.xml
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
- gazebo_ros2_control_demos/CMakeLists.txt
Since `gazebo_system_interface.hpp` includes urdf/model:
https://github.com/ros-simulation/gazebo_ros2_control/blob/698d01381423cea3232a78ab0ada7eb12cd6d40b/gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system_interface.hpp#L32
I guess also the CMake target gazebo_hardware_plugins should depend on urdf.
At least that fixed my build on Ubuntu 18.04.
> Declare dependency of gazebo_hardware_plugins to urdf in CMakeLists.txt

- gazebo_ros2_control/CMakeLists.txt
- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system_interface.hpp
- gazebo_ros2_control/package.xml
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
[Backport Foxy] Declare dependency of gazebo_hardware_plugins to urdf in CMakeLists.txt (#117)
> [Backport Foxy] Remove dependency of gazebo_hardware_plugins to urdf in CMakeLists.txt (#117)

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
It might be related with this issues https://github.com/ros-controls/gz_ros2_control/issues/62
hardware interfaces now have state logic around them, so they need to be set in the active state. I tried the command added in the issue
```
ros2 service call controller_manager/set_hardware_component_state controller_manager_msgs/srv/SetHardwareComponentState '{name: 'GazeboSimSystem', target_state: {id: 3, label: ""}}'
```
and it works but these few lines have the same effect
> Added logic for hardware interfaces

- gazebo_ros2_control_demos/config/diff_drive_controller.yaml
Adding the simulation parameter so that the controller manager uses the simulation time instead of the ROS time.  The '/odom' and corresponding tf will only be published if this parameter is set to true.
> Adding simulation time parameter for the controller manager

- gazebo_ros2_control_demos/CMakeLists.txt
Fixed CMake source file extension to avoid a warning in the buildfarm
> Fixed CMake source file extension

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Fixed name change making `GazeboSystem` `unavailable` according to #131 and #139
> changed name to GazeboSystem

- gazebo_ros2_control/src/gazebo_system.cpp
- gazebo_ros2_control_demos/urdf/test_cart_effort.xacro.urdf
This should fix #108.
The reason for the issue is that if the command interface does not exist, the initial value is never propagated to the simulator.
﻿
> Fix setting initial values if command interfaces are not defined.

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Default activation of hardware names `GazeboSystem` is very restrictive. Suggestion to set all hardware to `available` by default.
> activated all hardware by default

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Minor fix to allow CM to be run in the defined namespace, ref #122
> added namespace to controller manager

- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system.hpp
- gazebo_ros2_control/src/gazebo_system.cpp
This PR should fix https://github.com/ros-controls/gazebo_ros2_control/issues/85 by implementing the `perform_command_mode_switch` method override to set joint control methods when controllers are activated/deactivated.
> implemented perform_command_mode_switch override in GazeboSystem

- gazebo_ros2_control/src/gazebo_system.cpp
With this change gripper example works again.
> Mimic joint should have the same control mode as mimicked joint.

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
This fixes API break from
https://github.com/ros-controls/ros2_control/pull/780
> Rename hw info class type to plugin name

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
If the plugin is loaded with wrong parameters, e.g.
```urdf
<robot_param>wrong_robot_description</robot_param>
<robot_param_node>robot_state_publisher</robot_param_node>
```
the plugin crashed without console output of the segmentation fault. Now we get a more meaningful output.
> Improve error message if robot_description_ param is wrong

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
The same change as done for Gazebo Sim in ros_controls/gz_ros2_control#100
Should resolve issues like #156
>  Force setting use_sim_time parameter when using plugin.

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Cherry-pick https://github.com/ros-controls/gazebo_ros2_control/commit/cc5746bad6820a39d158eec87c0100126f78a6ab from `master` branch to force `use_sim_time` to true in humble
> [humble] Force setting use_sim_time parameter when using plugin.

- gazebo_ros2_control/CMakeLists.txt
While writing a specialized Hardware Interface for our robot, I realized that my library has compilation errors, if I do not `find_package` the Gazebo library. This is when I realized that only `ament_cmake` and `rclcpp` are currently exported. I took the liberty to export all dependencies currently `find_package`d.
See also the [Ament-CMake-Documentation](https://docs.ros.org/en/humble/How-To-Guides/Ament-CMake-Documentation.html#building-a-library) :
> The ament_export_dependencies exports dependencies to downstream packages. This is necessary so that the user of the library does not have to call find_package for those dependencies.
Should it be possible for other user to inherit from `GazeboSystemInterface` to create their custom interfaces?
If yes, I guess we should export all the …
> Export all dependencies

- gazebo_ros2_control_demos/config/tricycle_drive_controller.yaml
It was removed https://github.com/ros-controls/ros2_controllers/pull/468
> Remove publish_rate parameter

- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system_interface.hpp
Hi,
Here's a simple change to remove a compilation warning that is complaining about a copy assignment for the type `SafeEnum`.
It's also happening in humble so if you could create a backport it would be awesome :)
> Fix deprecated copy warning

- gazebo_ros2_control/src/gazebo_system.cpp
Following up with my remarks on https://github.com/ros-controls/gazebo_ros2_control/pull/177#issuecomment-1584743086 and a request for a PR.
summary: in the discussion of the [reset pos/vel commands](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/437/page/1) it is said that setting position/velocity for joints is overriding physics, and should generally not be used,
I know from past experience with enforcing pose of an object at each time step was not sufficient to hold it in place (drift), velocity had to be set to zero as well. I immediately related the joint sagging issue to that pose drift.
Solution is to set zero velocity as well for that time step. Setting velocity to zero after fixing position is another override that stabilizes the …
> Fix sagging robots in position control

- gazebo_ros2_control/package.xml
I think that the pluginlib macros in the export section are not necessary any more, `pluginlib_export_plugin_description_file` in CMakeLists does the job. See the official docs:
- https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Pluginlib.html#cmake-plugin-declaration
- https://github.com/ros/pluginlib/blob/6c441f70ed7fd3d75d61210b99f8e02954a6c9a3/pluginlib/cmake/pluginlib_export_plugin_description_file.cmake#L50-L65
> Remove plugin export (ROS 1 syntax)

- doc/index.rst
The example is not working any more, fixing #217.
Please also backport to humble.
> Remove Moveit2 example

- gazebo_ros2_control/src/gazebo_system.cpp
Related with this comment https://github.com/ros-controls/gazebo_ros2_control/pull/177#issuecomment-1674842288
> Removed unused var

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
I recently worked with custom simulation plugins as described [in the docs](https://control.ros.org/master/doc/gazebo_ros2_control/doc/index.html#advanced-custom-gazebo-ros2-control-simulation-plugins).
It took me a while to debug the ClassLoader, I propose a catch on pluginlib exceptions.
As an example, a non-existing plugin name in the urdf
```xml
<hardware>
<plugin>gazebo_ros2_control_actuators/GazeboSystemWrong</plugin>
</hardware>
```
was just not loaded and gzserver died. Now it is catched with the following error message
```
[gzserver-1] [ERROR] [1692356394.343300163] [gazebo_ros2_control]: The plugin failed to load for some reason. Error: According to the loaded plugin descriptions the class gazebo_ros2_control/GazeboSystemWrong with base class type …
```
> Catch pluginlib exceptions

- gazebo_ros2_control_demos/config/cartpole_controller_effort.yaml
- gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml
- gazebo_ros2_control_demos/examples/example_effort.cpp
- gazebo_ros2_control_demos/launch/cart_example_effort.launch.py
The controller config of the velocity and effort controllers (specializations of the forward_command_controller) had some non-existing parameters in the yaml.
See the config files in the [demo repository](https://github.com/ros-controls/ros2_control_demos/blob/master/example_3/bringup/config/rrbot_multi_interface_forward_controllers.yaml) or the [PR to update the docs](https://github.com/ros-controls/ros2_controllers/pull/765).
> Cleanup controller config

- .github/workflows/ci.yaml
CI is not activated for branches other than master:
[![Gazebo ros2 control CI](https://github.com/ros-controls/gazebo_ros2_control/actions/workflows/ci.yaml/badge.svg?branch=humble)](https://github.com/ros-controls/gazebo_ros2_control/actions/workflows/ci.yaml)
I don't think this is on purpose?
> Activate CI for humble

- gazebo_ros2_control/src/gazebo_system.cpp
As mentioned in #235 and #219, a problem with passive joints was introduced by the following code line: 
https://github.com/ros-controls/gazebo_ros2_control/blob/0dc19ab5561f7ef6b6d9addee55a4b01c56de126/gazebo_ros2_control/src/gazebo_system.cpp#L597-L600
As suggested by @destogl, I added a vector with flags which indicates if a joint is active (has command interfaces) or passive and subsequently sets the velocity to zero or not.
> Fix stuck passive joints

- gazebo_ros2_control_demos/launch/tricycle_drive.launch.py
flake8 is complaining about double quotes. I'm not sure why [this CI job fails](https://github.com/ros-controls/control.ros.org/actions/runs/6917705161/job/18819180709#step:6:24195) and others don't, but this is a simple fix.
> Replace double quotes with single ones

- doc/index.rst
- gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system.hpp
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
- gazebo_ros2_control/src/gazebo_system.cpp
@HPCLOL posted a use case of gazebo in https://github.com/ros-controls/ros2_controllers/issues/875:
If the simulation is started with an inactive controller, the robot should move with gravity as if the joints were passive.
As discussed with #250 this is currently not possible. This PR adds an parameter to enable this behavior (again). 
- I'm not sure if this should be default true or false.
- I haven't found a different solution to tell `GazeboSystem` this parameter parsed from the gazebo plugin without changing API. Therefore, I used a ROS parameter of the gazebo_ros2_control node to pass the information.
The result looks like this if no controller was spawned:
https://github.com/ros-controls/gazebo_ros2_control/assets/3367244/45e2f56a-7173-4cee-a30e-02713127c63b
> Add `hold_joints` parameter

- gazebo_ros2_control_demos/config/diff_drive_controller.yaml
- gazebo_ros2_control_demos/config/tricycle_drive_controller.yaml
- gazebo_ros2_control_demos/examples/example_diff_drive.cpp
- gazebo_ros2_control_demos/examples/example_tricycle_drive.cpp
Replace `Twist` with `TwistStamped`. Related with TwistStamped transition https://github.com/ros-planning/navigation2/pull/3775
> replace Twist with TwistStamped

- .github/workflows/ci-rolling.yaml
I saw these [error messages](https://github.com/ros-controls/gazebo_ros2_control/actions/runs/7476086437/job/20345684887?pr=255) when building rolling
```bash
W: GPG error: http://packages.ros.org/ros2-testing/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: The repository 'http://packages.ros.org/ros2-testing/ubuntu jammy InRelease' is not signed.
```
> Rolling CI add sign from ROS2 packages

- README.md
- gazebo_ros2_control/README.md
* Fix links for Gazebo Classic to point to https://classic.gazebosim.org/ instead of https://gazebosim.org/ that is related to modern Gazebo libraries.
* Fix link to the documentation to point to https://control.ros.org/master/doc/gazebo_ros2_control/doc/index.html instead of non-working (at least for me) https://control.ros.org/master/doc/simulators/gazebo_ros2_control/doc/index.html URL
fyi @AleTarsi
> Fix links in documentation

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
These changes are needed after the merging of https://github.com/ros-controls/ros2_control/pull/1271 and https://github.com/ros-controls/ros2_control/pull/1272. It seems like the gazebo_ros2_control doesn't load the URDF into the resource manager, and this is causing the CM services not to start.
However, loading the URDF with the [`load_urdf`](https://github.com/ros-controls/ros2_control/blob/3309c6dbaf4ab5140d13908bedb6fb471c422498/hardware_interface/src/resource_manager.cpp#L759-L796) method will probably fail, because this method originally loads and initializes the hardware interfaces and this step might probably fail. For this reason, I'm catching the exception here, but the overall behaviour will work.
If approved, this will need backport to Iron and Humble
Needs: …
> Load the URDF to the resource_manager before parsing it to CM 

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
This merge resolves the issue with robot description parameter in controller manager and controllers.
Some custom controllers require information about robot description, which are available normally over a parameter of controller manager and controllers in the ros2 control. However, this parameter was missing, if the controller manager (as well controllers) is started over gazebo ros2 control. Therefore, the custom controllers could not be used/tested with the gazebo.
I tested this code with my custom controllers. 
If you have some remarks, I would be glad to introduce some improvement.
Here is an output of parameter list before (without robot description parameter):
```
/controller_manager:
forward_position_controller.type
joint_state_broadcaster.type …
```
> set the robot description parameter

- gazebo_ros2_control_demos/config/cart_controller.yaml
- gazebo_ros2_control_demos/package.xml
Two minimal changes to the demos:
- no need for `interface_name: position`
- no dependency on ros2_controllers (all controllers are listed explicitly)
> Cleanup of demos

- gazebo_ros2_control/src/gazebo_system.cpp
Fix https://github.com/ros-controls/gazebo_ros2_control/issues/218
I noticed that there is no force-torque sensor example in this repository. Should we add one?
> Fix incorrect force-torque sensor vec population

- gazebo_ros2_control_demos/urdf/test_pendulum_effort.xacro.urdf
- gazebo_ros2_control_demos/urdf/test_pendulum_position.xacro.urdf
> Now it's moving:
Passive joints were always "moving", but as if they were fixed in inertial frame. A movement of the parent link did not effect the respective joint.
For demonstration purposes, I change the initial pose to be in the lower equilibrium to make this clearer:
https://github.com/ros-controls/gazebo_ros2_control/assets/3367244/630cc8b8-6cb4-4dbc-9caa-948c085052e0
_Originally posted by @christophfroehlich in https://github.com/ros-controls/gazebo_ros2_control/issues/172#issuecomment-2105185043_
> Change initial pose of pendulum example

- gazebo_ros2_control/src/gazebo_system.cpp
```
/workspaces/ros2_baustelle_ws/src/ros-controls/gazebo_ros2_control/gazebo_ros2_control/src/gazebo_system.cpp: In member function ‘control_toolbox::Pid gazebo_ros2_control::GazeboSystem::extractPID(std::string, hardware_interface::ComponentInfo)’:
/workspaces/ros2_baustelle_ws/src/ros-controls/gazebo_ros2_control/gazebo_ros2_control/src/gazebo_system.cpp:231:93: warning: ‘antiwindup’ may be used uninitialized in this function [-Wmaybe-uninitialized]
231 |   return control_toolbox::Pid(kp, ki, kd, max_integral_error, min_integral_error, antiwindup);
|                                                                                             ^
```
> Initialize antiwindup variable properly

- gazebo_ros2_control_demos/config/diff_drive_controller.yaml
- gazebo_ros2_control_demos/config/tricycle_drive_controller.yaml
Is default true already, and will be removed by https://github.com/ros-controls/ros2_controllers/pull/1151
> Remove stamped twist parameter

- doc/index.rst
- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
These changes are necessary to adjust compatibility with cleanup done in ros-controls/ros2_control#1354.
This is a rewrite of https://github.com/ros-controls/gz_ros2_control/pull/265 adapted for gazebo_ros2_control. I tested it successfully with the demos . 
gazebo_ros2_control won't be released for rolling distro on noble, but this PR repairs the [compatibility for the ros2_control rolling version on humble/iron](https://github.com/ros-controls/ros2_control_ci/actions/workflows/rolling-compatibility-humble-binary-build.yml).
> Simplify access for robot description from CM by overriding RM

- gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Needs: https://github.com/ros-controls/ros2_control/pull/1585
This changes helps to use the clock and logging interface of the node directly.
> Propagate the node clock and logging interface to ResourceManager
