ros-controls/gazebo_ros2_control

gazebo_ros2_control/CMakeLists.txt, gazebo_ros2_control/include/gazebo_ros2_control/default_robot_hw_sim.hpp, gazebo_ros2_control/include/gazebo_ros2_control/gazebo_ros2_control_plugin.hpp, gazebo_ros2_control/package.xml, gazebo_ros2_control/src/default_robot_hw_sim.cpp
Alphabetize headers, package.xml and CMakeList.txt
=> alphabetize headers, package.xml and CMakeList.txt

gazebo_ros2_control/include/gazebo_ros2_control/gazebo_ros2_control_plugin.hpp
This allows me to compile the `master` branch using the instructions on #12, with some extra changes that I'll write there.
=> Fix compilation on master

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
=> Removed legacyModeNS tag

gazebo_ros2_control/src/default_robot_hw_sim.cpp, gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
related with this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/15
=> Only support Gazebo 9+

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
=> Used node logger

gazebo_ros2_control/src/default_robot_hw_sim.cpp
there's only 1 buffer for now, we should register the right command_handle
=> Register the right cmd_handle

.github/workflows/ci.yaml
=> Use rosdep to install dependencies in CI

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Related to this issue
- https://github.com/ros-simulation/gazebo_ros2_control/issues/22
=> plugins tag to snake_case

.github/workflows/ci.yaml
Upgrade packages in the CI but this still needs a release from rcpputils as requested [here](https://github.com/ros2/rcpputils/issues/89)
=> Upgrade packages in CI

.github/workflows/ci.yaml
=> CI - installed realtime-tools and xacro from packages

gazebo_ros2_control_demos/launch/cart_example_position.launch.py, gazebo_ros2_control_demos/launch/cart_example_position_pid.launch.py, gazebo_ros2_control_demos/launch/cart_example_velocity.launch.py
I didn't add these changes to https://github.com/ros-simulation/gazebo_ros2_control/pull/2
it will use the topic instead of the tmp file.
=> Fixed demo launch files

gazebo_ros2_control_demos/config/cartpole_controller_effort.yaml, gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml
Related with this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/50
=> Fixed config value for velocity and effort yaml

gazebo_ros2_control/src/gazebo_system.cpp
Related with this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/52
FYI @olivier-stasse
=> Fixed state interfaces

LICENSE, gazebo_ros2_control/package.xml
Required to release the package https://github.com/ros/rosdistro/pull/28250
=> Added License file

gazebo_ros2_control_demos/package.xml
fixes #49
once merged, I believe this needs a re-release
=> add ros2_controllers as exec dependency

gazebo_ros2_control_demos/package.xml
Related with this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/62
=> Add effort_controller exec_depend on demos

gazebo_ros2_control_demos/config/cartpole_controller_effort.yaml, gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml
Related with this issue https://github.com/ros-simulation/gazebo_ros2_control/issues/57
=> Remove Unnecessary parameter in demo

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Fixes https://github.com/ros-simulation/gazebo_ros2_control/issues/66
=> Write joints on each simulation update period

gazebo_ros2_control_demos/config/cartpole_controller.yaml, gazebo_ros2_control_demos/config/cartpole_controller_effort.yaml, gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml, gazebo_ros2_control_demos/launch/cart_example_effort.launch.py, gazebo_ros2_control_demos/launch/cart_example_position.launch.py, gazebo_ros2_control_demos/launch/cart_example_velocity.launch.py
=> Update code with recent change in ros2_control

gazebo_ros2_control_demos/examples/example_position.cpp
Fix messages in `example_position.cpp` that were incorrectly set as `ERROR`
=> Update severity of msgs to proper level

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp, gazebo_ros2_control_demos/launch/cart_example_velocity.launch.py
This PR depends on this other PR in `ros2_control` https://github.com/ros-controls/ros2_control/pull/566 
This fixes the issues in the Galactic release https://github.com/ros-simulation/gazebo_ros2_control/issues/84#issuecomment-952263039 and this other open issue in `ros2_control` https://github.com/ros-controls/ros2_control/issues/550
=> Fix ros2_control resource manager in Galactic

Docker/Dockerfile
=> Update Foxy Dockerfile

Docker/Dockerfile
This will not compile, waiting the next ROS 2 Galactic sync.
=> Update Galactic Dockerfile

Docker/entrypoint.sh
The entry point needs to be updated to source /opt/ros/galactic instead of foxy
=> The Dockerfile in the main branch now uses galactic

.github/workflows/ci.yaml, Docker/Dockerfile, Docker/entrypoint.sh
Updated `master` branch to `rolling`
=> Updated master branch to rolling

gazebo_ros2_control/src/gazebo_system.cpp
Tested with the gripper example.
=> Fix mimic joint for effort command

gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system.hpp, gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp, gazebo_ros2_control/src/gazebo_system.cpp
Check ros-controls/ros2_control#673 for more info. This breaks build of the plugin.﻿
=> ros2_control is now having usings under its namespace.

gazebo_ros2_control_demos/launch/diff_drive.launch.py
Changed misprinted variable name.
=> Changed launch variable name

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
This PR improves fixes in #143, #142, #139.
It makes the naming of variable more straightforward for further changes.
I also did the same fix as in #143 at first, and then found out that the variable name is a bit confusing, as it was hard to find it at first.
=> 🚀 Improve variable naming to simpler debug and extend the functionality.

gazebo_ros2_control_demos/launch/cart_example_effort.launch.py, gazebo_ros2_control_demos/launch/cart_example_position.launch.py, gazebo_ros2_control_demos/launch/cart_example_velocity.launch.py, gazebo_ros2_control_demos/launch/diff_drive.launch.py, gazebo_ros2_control_demos/launch/gripper_mimic_joint_example.launch.py
Fixed controllers in demos not launching. Replaced all `--set-state start` by `--set-state active`.
=> fix demo launch

README.md, gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system.hpp, gazebo_ros2_control/package.xml, gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp, gazebo_ros2_control/src/gazebo_system.cpp, gazebo_ros2_control_demos/package.xml
Backported
- #136
- #147
- #139 
- #134
=> [backport Foxy] #136 #147 #139 #134

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
[Backport Foxy] Enable loading params from multiple yaml files (#149)
=> [Backport Foxy] Enable loading params from multiple yaml files (#149)

gazebo_ros2_control_demos/config/diff_drive_controller.yaml
Co-authored-by: Eslam Salah <eslamsalahelsheikh@gmail.com>
=> Adding simulation time parameter for the controller manager (#138) 

gazebo_ros2_control/include/gazebo_ros2_control/gazebo_system_interface.hpp
Signed-off-by: Alejandro Hernández Cordero <ahcorde@gmail.com>
Related with this build https://build.ros2.org/job/Rdev__gazebo_ros2_control__ubuntu_jammy_amd64/21/gcc/new/folder.-1966411666/
=> Removed warning

.github/workflows/ci-format.yaml, .pre-commit-config.yaml, README.md, gazebo_ros2_control/CHANGELOG.rst, gazebo_ros2_control/src/gazebo_system.cpp, gazebo_ros2_control_demos/CHANGELOG.rst
=> Foxy to galactic

gazebo_ros2_control/src/gazebo_system.cpp
Just a straightforward port of this PR from `gz_ros2_control`:
https://github.com/ros-controls/gz_ros2_control/pull/114
=> Various bug fixes

.github/workflows/ci.yaml
Signed-off-by: Alejandro Hernández Cordero <ahcorde@gmail.com>
=> Fixed humble CI

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
New PR cause I don't have write access to #230
=> Fix merge conflict (backport #229) #230

gazebo_ros2_control/src/gazebo_system.cpp
Use own implementation of `stod()`, see https://github.com/ros-controls/ros2_control/pull/1257
=> Use own implementation of `stod()`

.github/workflows/ci-humble.yaml, .github/workflows/ci-iron.yaml, .github/workflows/ci-rolling.yaml
This should fix the issue in CI https://github.com/ros-controls/gazebo_ros2_control/pull/267
=> Fix sign CI

gazebo_ros2_control_demos/examples/example_diff_drive.cpp
Fixing a small error merged with #249
=> Fix diff_drive example

.github/workflows/update-pre-commit.yml, .pre-commit-config.yaml, gazebo_ros2_control/src/gazebo_system.cpp
Auto-update the pre-commit config once per month.
=> Update precommit config

doc/index.rst
It seems that I missed this while fixing merge conflicts.
=> [docs] Remove duplicate image

.github/workflows/ci-check-docs.yml
The branch renamed from master -> rolling
=> [CI] Fix branch of reusable workflow

gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
Changes to have remapping. A similar approach to: https://github.com/ros-controls/ros2_control/pull/1712
=>  propagate gazebo remapping and other arguments to the controller node

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/good-first-issue.md
=> Add issue_templates

gazebo_ros2_control/src/gazebo_system.cpp
https://github.com/ros-controls/control_toolbox/pull/246
=> Update API of PID class
